# -*- coding: utf-8 -*-
"""28_sept_RFC_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kzr0y9J9SFgOz9cm4AQPa8ot9iS7UfZl
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

from sklearn.datasets import load_iris

iris = load_iris()

d = {'name':'dany','mobile':9545243192}

d

d['mobile']

iris

iris['data']

iris['target']

iris['feature_names']

dataset = pd.DataFrame(iris['data'],columns=iris['feature_names'])

dataset

dataset['class_label'] = iris['target']

dataset

X = dataset.iloc[:,0:4].values

X

y = dataset.iloc[:,4].values

y

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

X_train.shape

X_train

y_train

X_test.shape

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=10,max_depth=10,max_leaf_nodes=7)

model.fit(X_train,y_train)

model.score(X,y)

# evaluation

y_pred = model.predict(X_test)

y_pred

y_test

from sklearn.metrics import confusion_matrix,classification_report

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

